---
title: "HighDimensionResearch"
author: "John Leland"
date: "2022-11-09"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(TDA)
modelling1 <- function(n,d, maxdimension,maxscale, classy = "NA"){


DiagRips <- ripsDiag(X = d, maxdimension, maxscale,
                     library = c("GUDHI", "Dionysus"), location = TRUE, printProgress=FALSE)

Barlength <- (DiagRips$diagram[,3] - DiagRips$diagram[,2])*n^(-1/ncol(d))
return(Barlength)
}

hoverlaygamma <- function(n, s=1,g =1, dim = 2){
  gamma <- matrix(c(rgamma(n,s,g),rgamma(n,s,g)), ncol = dim)
  modelling1(n,gamma,0,max(gamma))
}

hoverlaynorm <- function(n, mean = 0, sd = 1, dim = 2){
  norm <- matrix(c(rnorm(n,mean,sd),rnorm(n,mean,sd)), ncol = dim)
  modelling1(n,norm,0,max(norm))
}

hoverlaycauchy <- function(n,s = 1, j = 1, dim = 2){
  cauchy <- matrix(c(rcauchy(n,s,j),rcauchy(n,s,j)), ncol = dim)
  modelling1(n,cauchy,0,max(cauchy))
}

hoverlayt <- function(n,s =1,j  =1, dim = 2){
  t <- matrix(c(rt(n,s,j),rt(n,s,j)), ncol = dim)
  modelling1(n,t,0,max(t))
}

hoverlayunif <- function(n, min = 0 ,max = 1, dim = 2){
  unif <- matrix(c(runif(n,min,max), runif(n,min,max)), ncol = dim)
  modelling1(n,unif,0,max(unif))
}

hoverlaybeta <- function(n, s1 = 0 ,s2 = 1, dim = 2){
  beta <- matrix(c(rbeta(n,s1,s2), runif(n,s1,s2)), ncol = dim)
  modelling1(n,beta,0,max(beta))
}
```


```{r}

library(parallel)
integrationdifference <- function(n,f1,f2, p1,p2,p3,p4,dim){
  b1 <- sapply(n,f1,p1,p2,dim)
  b2 <- sapply(n,f2,p3,p4,dim)
  
  
  e <- ecdf(b1)
 e2 <- ecdf(b2)
 
 
 b1.partial <- cumsum(b1) / length(b1)
i1 <- which.max(b1.partial > 0.1)
m1 <- ceiling(b1[i1])+1

b2.partial <- cumsum(b2) / length(b2)
i2 <- which.max(b2.partial > 0.1)
m2 <- ceiling(b2[i2])+1

upper <- ifelse(m1 >= m2,m1,m2)

  i1 <- integrate(e, 0, upper, subdivisions = 2000)
  i2 <- integrate(e2, 0, upper, subdivisions = 2000)
  
  abs(i1$value - i2$value)
}
```


```{r}
library(mcreplicate)
b<- 100
set.seed(700)
seq <- seq(1,10, by = 1)
opendifference <- c()
for(i in seq){
int <- mc_replicate(b, integrationdifference(300, hoverlaynorm, hoverlayunif, p1= i, p2 = 2*i, p3 = 0,p4 = 1, dim = 3), mc.cores = 6)
opendifference = c(opendifference,int)

}
```

```{r}
library(mcreplicate)
b<- 100
set.seed(700)
opensame <- c()
for (i in seq){
int <- mc_replicate(b, integrationdifference(300, hoverlaynorm, hoverlaynorm, p1= i, p2 = 2*i, p3 = i, p4 = 2*i, dim = 3), mc.cores = 6)
opensame <- append(opensame, int)
}
```



```{r}
vecouts <- c(opensame,opendifference)
d <- rep(0, times = length(opendifference))
c <- rep(1, times = length(opensame))
yes <- c(c,d)
length(yes)
dat <- data.frame(vecouts, yes)

```

```{r}
library(ggplot2)
ggplot(dat, aes(x = vecouts, y = yes))+
  geom_point()+xlab("Absolute Integrated Ecdf Difference")+
  ylab("Same = 1: Different = 0")
```

```{r, warning = FALSE}
library(boot)
glm.fit <- glm(I(yes==1)~vecouts, data=dat, family='binomial')
cost <- function(r, pi = 0) mean(abs(r-pi) > 0.5)

cv.glm(dat,glmfit = glm.fit,cost,K = 10)$delta[1]
```



```{r}
summary(glm(I(yes==1)~vecouts, data=dat, family='binomial'))
```



```{r}

library(parallel)
integration <- function(n,f1,f2, p1 = 1,p2 = 1,p3 =1,p4 = 1,dim,...){
  b1 <- sapply(n,f1,p1,p2)
  m1 <- matrix(c(b1), ncol = dim)
  b2 <- sapply(n,f2,p3,p4)
  m2 <- matrix(c(b2), ncol = dim)
  
  
  e <- ecdf(m1)
 e2 <- ecdf(m2)
 
b1.partial <- cumsum(b1) / length(b1)
i1 <- which.max(b1.partial > 0.1)
g1 <- ceiling(b1[i1])+1

b2.partial <- cumsum(b2) / length(b2)
i2 <- which.max(b2.partial > 0.1)
g2 <- ceiling(b2[i2])+1

upper <- ifelse(g1 >= g2,g1,g2)
  i1 <- integrate(e, 0, upper, subdivisions = 2000)
  i2 <- integrate(e2, 0, upper, subdivisions = 2000)
  
  abs(i1$value - i2$value)
}
```

```{r}
set.seed(700)
b<- 100
opendifference <- c()
opensame <- c()
for(i in seq){
int <- mc_replicate(b, integration(300, rnorm, runif, p1 = i, p2 = 2*i, p3 = 0, p4 = 1, dim = 3), mc.cores = 6)

opendifference = c(opendifference,int)

int <- mc_replicate(b, integration(300, rnorm, rnorm, p1 = i,p2 = 2*i, p3 = i,p4 = 2*i, dim = 3), mc.cores = 6)
opensame <- append(opensame, int)

}
```


```{r}
vecouts2 <- c(opensame,opendifference)
d2 <- rep(0, times = length(opendifference))
c2 <- rep(1, times = length(opensame))
yes2 <- c(c2,d2,recursive = TRUE)
length(yes2)
dat2 <- data.frame(vecouts2, yes2)
```

```{r}
plot(dat2)

```

```{r, warning = FALSE}
library(boot)
glm.fit <- glm(I(yes2==1)~vecouts2, data=dat2, family='binomial')
cost <- function(r, pi = 0) mean(abs(r-pi) > 0.5)

cv.glm(dat2,glmfit = glm.fit,cost,K = 10)$delta[1]
```




```{r}
library(mcreplicate)
b<- 100
set.seed(700)
seq <- seq(1,10, by = 1)
opendifference2 <- c()
for(i in seq){
int <- mc_replicate(b, integrationdifference(100, hoverlaycauchy, hoverlaynorm, p1= i, p2 = 2*i, p3 = i,p4 = 2*i, dim = 2), mc.cores = 6)
opendifference2 = c(opendifference2,int)

}
```

```{r}
library(mcreplicate)
b<- 100
set.seed(700)
opensame2 <- c()
for (i in seq){
int <- mc_replicate(b, integrationdifference(100, hoverlaycauchy, hoverlaycauchy,p1= i, p2 = 2*i, p3 = i, p4 = 2*i, dim = 2), mc.cores = 6)
opensame2 <- append(opensame2, int)
}
```



```{r}
vecout <- c(opensame2,opendifference2)
d <- rep(0, times = length(opendifference2))
c <- rep(1, times = length(opensame2))
y <- c(c,d)
length(y)
dat3 <- data.frame(vecout, y)

```


```{r}
ggplot(dat3, aes(x= vecout, y = y))+
    geom_point()+xlab("Absolute Integrated Ecdf Difference")+
  ylab("Same = 1: Different = 0")
```

```{r, warning = FALSE}
library(boot)
glm.fit <- glm(I(y==1)~vecout, data=dat3, family='binomial')
cost <- function(r, pi = 0) mean(abs(r-pi) > 0.5)

cv.glm(dat3,glmfit = glm.fit,cost,K = 10)$delta[1]
```


```{r}
fitchoice = glm(I(y==1)~vecout, data=train_set, family='binomial')
summary(fitchoice)

f <- function(x){
  1/(1+exp(-3.8437+0.5747*x))
}

f(3)
```


```{r}
set.seed(700)
b<- 100
opendifference <- c()
opensame <- c()
for(i in seq){
int <- mc_replicate(b, integration(100, rcauchy, rnorm, p1 = i, p2 = 2*i, p3 = i, p4 = 2*i, dim = 2), mc.cores = 6)

opendifference = c(opendifference,int)

int <- mc_replicate(b, integration(100, rcauchy, rcauchy, p1 = i,p2 = 2*i, p3 = i,p4 = 2*i, dim = 2), mc.cores = 6)
opensame <- append(opensame, int)

}
```


```{r}
vecouts3 <- c(opensame,opendifference)
d3 <- rep(0, times = length(opendifference))
c3 <- rep(1, times = length(opensame))
yes3 <- c(c3,d3,recursive = TRUE)
length(yes3)
dat4 <- data.frame(vecouts3, yes3)
```

```{r}
plot(dat4)
```


```{r}
glm.fit2 <- glm(I(yes3==1)~vecouts3, data=dat4, family='binomial')
cost <- function(r, pi = 0) mean(abs(r-pi) > 0.5)

cv.glm(dat4,glmfit = glm.fit2,cost,K = 10)$delta[1]
```




```{r}
ksave <- c()
set.seed(7)
for(i in 1:100){
  for(j in 1:10){
  n1 <- matrix(c(rnorm(100,j,2*j)),ncol = 1)
  n2 <- matrix(c(rnorm(100,j,2*j)),ncol =1)
  kssave <- ks.test(n1,n2)
  tester <- ifelse(kssave$p.value < 0.05,1,0)
  ksave <- append(ksave,tester)
  }
}
```

```{r}
length(ksave)
mean(ksave)
```

```{r}
ksaved <- c()
set.seed(7)
for(i in 1:100){
  for(j in 1:10){
  n1 <- matrix(c(rnorm(100,j,2*j)),ncol = 1)
  n2 <- matrix(c(runif(100,0,1)),ncol =1)
  kssaved <- ks.test(n1,n2)
  tester <- ifelse(kssaved$p.value < 0.05,1,0)
  ksaved <- append(ksaved,tester)
  }
}
```

```{r}
mean(ksaved)
```



```{r}
library(mcreplicate)
b<- 500
set.seed(700)
seq <- seq(1,10, by = 1)
opendifference <- c()
for (i in seq){
int <- mc_replicate(b, integrationdifference(100, hoverlaynorm, hoverlayunif, p1= 0, p2 = i, p3 = 0,p4 = 1, dim = 2), mc.cores = 6)
opendifference = c(opendifference,int)
}
```


```{r}
library(mcreplicate)
b<- 500
set.seed(700)
opensame <- c()
for (i in seq){
int <- mc_replicate(b, integrationdifference(100, hoverlaynorm, hoverlaynorm, p1= 0, p2 = i, p3 = 0, p4 = i, dim =2), mc.cores = 6)
opensame <- append(opensame, int)
}
```
```{r}
vecouts <- c(opensame,opendifference)
d2 <- rep(0, times = length(opendifference))
c2 <- rep(1, times = length(opensame))
yes <- c(c2,d2,recursive = TRUE)
length(yes)
dat.1 <- data.frame(vecouts, yes)
plot(dat.1)
opensame
```


```{r, warning=FALSE}
glm.fit3 <- glm(I(yes==1)~vecouts, data=dat.1, family='binomial')
cost <- function(r, pi = 0) mean(abs(r-pi) > 0.5)

cv.glm(dat.1,glmfit = glm.fit3,cost,K = 10)$delta[1]
summary(glm.fit3)
```


```{r}
library(fasano.franceschini.test)

ks3 <- function(n,f1,f2, p1 = 1,p2 = 1,p3 =1,p4 = 1,...){
  b1 <- sapply(n,f1,p1,p2)
  m1 <- matrix(c(b1), ncol = 3)
  b2 <- sapply(n,f2,p3,p4)
  m2 <- matrix(c(b2), ncol = 3)
  
  ks <- fasano.franceschini.test(m1,m2)
  
  ksd <- ks
}
```

```{r}
# perform test
kk <- c()
library(mcreplicate)
set.seed(700)
for(i in seq(1,10,by = 10)){
jk <- mc_replicate(100, ks3(300, rnorm, rnorm, p1= i, p2 = 2*i, p3 = i, p4 = 2*i), mc.cores = 6)
kk <- append(kk,jk)
}

```

```{r}
mean(ifelse(unlist(kk) < 0.1, 1,0))
```


```{r}
hist(opensame)
quantile(opensame, 0.95)

quantileexp <- function(p,l){
  -(log(1-p)/l)
  
}

log(100)
quantileexp(0.95, 100)
```

```{r}
library(mcreplicate)
b<- 100
set.seed(700)
seq <- seq(1,5, by = 1)
opendifference <- c()
for (i in seq){
int <- mc_replicate(b, integrationdifference(200, hoverlayunif, hoverlayunif, p1= 0, p2 = 1, p3 = 0,p4 = 1, dim = 2), mc.cores = 6)
opendifference = c(opendifference,int)
}
```




```{r}
library(fitdistrplus)
library(heplots)
smalllam <- c()
for(i in 1:600){
c <- qexp(0.99, i)
counter <- mean(ifelse(opendifference > c,1,0))
smalllam <- append(smalllam, counter)
}
dist <- fitdist(opendifference, "exp", method = "mle")
summary(dist)
plot(dist)
```
```{r}
set.seed(90)
seq <- seq(1,5, by = 1)
opendifference.20dim <- c()
for (i in seq){
int <- mc_replicate(b, integrationdifference(4000, hoverlaynorm, hoverlaynorm, p1= 0, p2 = 1, p3 = 0,p4 = 1, dim = 40), mc.cores = 6)
opendifference.20dim = c(opendifference.20dim,int)
}
```


```{r}
n = 200
m = 200
k = 40
c = (0.01)^(k-1)
crit = -log(c)/(n+m)
crit
counter <- mean(ifelse(opendifference.20dim > crit,1,0))
counter
```


